name: Deploy to VM Server

on:
  push:
    branches:
      - main

env:
  IP_ADDRESS: 144.24.130.225

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup SSH Key
      uses: shimataro/ssh-key-setup-action@v0.4.0
      with:
        private-key: ${{ secrets.SSH_KEY }}
        known-hosts: ${{ env.IP_ADDRESS }}
    
    - name: Deploy to VM Server
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ env.IP_ADDRESS }} "cd <your_destination_folder> && git pull"
