name: Deploy to VM Server

on:
  push:
    branches:
      - main

env:
  IP_ADDRESS: 144.24.130.225

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup SSH Key
      uses: actions/upload-ssh-key@v1
      with:
        username: <your_username>
        private-key: ${{ secrets.SSH_KEY }}
    
    - name: Add known host
      run: |
        echo "${{ env.IP_ADDRESS }} ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9dpIq3M4WL22QLLeDYIgKjnZlxWlDR8gIjKX9nQfogasLWy5b5a5g5kk5K7dzvIUhWg/iCQ3l4Om57
